name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Display Repository Files
        run: ls -la

      - name: Display HTML File
        run: cat index.html

      - name: Workflow Fixed
        run: echo "Workflow Fixed!"
